Connected to quarto_env (Python 3.13.10)

In [ ]:
import sqlite3
import pandas as pd

df = pd.read_csv('data/AllCounts_V_4_4.csv')
conn = sqlite3.connect('data/penguins_sights.db')

In [ ]:
# Moving data to the DB
df.to_sql('observations', conn, if_exists='replace',index=False)

5407

In [ ]:
c = conn.cursor()

# basics of the database
x = c.execute("SELECT name, type FROM sqlite_master;")

# checking the objects in the database
objects = x.fetchall()

for name, type in objects:
        print(f"I found a {type} called: {name}")

I found a table called: observations

In [ ]:
# checking the fields and data types
c.execute("PRAGMA table_info(observations);")
columns = c.fetchall()
print(columns)

[(0, 'site_name', 'TEXT', 0, None, 0), (1, 'site_id', 'TEXT', 0, None, 0), (2, 'cammlr_region', 'TEXT', 0, None, 0), (3, 'longitude_epsg_4326', 'REAL', 0, None, 0), (4, 'latitude_epsg_4326', 'REAL', 0, None, 0), (5, 'common_name', 'TEXT', 0, None, 0), (6, 'day', 'REAL', 0, None, 0), (7, 'month', 'REAL', 0, None, 0), (8, 'year', 'INTEGER', 0, None, 0), (9, 'season_starting', 'INTEGER', 0, None, 0), (10, 'penguin_count', 'REAL', 0, None, 0), (11, 'accuracy', 'REAL', 0, None, 0), (12, 'count_type', 'TEXT', 0, None, 0), (13, 'vantage', 'TEXT', 0, None, 0), (14, 'reference', 'TEXT', 0, None, 0)]

In [ ]:
c.execute("SELECT * FROM observations LIMIT 1;")
row = c.fetchone()
print(row)

('Acuna Island', 'ACUN', '48.2', -44.637, -60.761, 'adelie penguin', None, None, 1993, 1993, 2008.0, 1.0, 'nests', 'ground', '<p id="coria2011laurie" class="reference">Coria  N. R.  D. Montalti  E. F. Rombol&aacute;  et al. (2011). &ldquo;Birds at Laurie Island  South Orkney Islands  Antarctica: Breeding species and their distribution&rdquo;. In: <em>Marine Ornithology</em> 39.2  pp. 207&ndash;213.</p>')

In [ ]:
different_sites= c.execute("SELECT count( DISTINCT site_id) FROM observations;")
print("Different Sites:", different_sites.fetchall())

print("Count of Different Sites:", different_sites)

Different Sites: [(725,)]
Count of Different Sites: <sqlite3.Cursor object at 0x117853340>

In [ ]:
different_sites= c.execute("SELECT count( DISTINCT site_id) FROM observations;")
print("Different Sites:", different_sites.fetchall())

print("Count of Different Sites:", different_sites.fetchall)

Different Sites: [(725,)]
Count of Different Sites: <built-in method fetchall of sqlite3.Cursor object at 0x117853340>

In [ ]:
different_sites= c.execute("SELECT count( DISTINCT site_id) FROM observations;")
print("Different Sites:", different_sites.fetchall())

print("Count of Different Sites:", different_sites.fetchall())

Different Sites: [(725,)]
Count of Different Sites: []

In [ ]:
different_sites= c.execute("SELECT count( DISTINCT site_id) FROM observations;")
print("Different Sites:", different_sites.fetchall())

print("Count of Different Sites:", different_sites.fetchall(1))

Different Sites: [(725,)]

TypeError: Cursor.fetchall() takes no arguments (1 given)

In [ ]:
different_sites= c.execute("SELECT count( DISTINCT site_id) FROM observations;")
print("Different Sites:", different_sites.fetchall())

print("Count of Different Sites:", different_sites.fetchall()[1])

Different Sites: [(725,)]

IndexError: list index out of range

In [ ]:
different_sites= c.execute("SELECT count( DISTINCT site_id) FROM observations;")
print("Different Sites:", different_sites.fetchall())

print("Count of Different Sites:", different_sites.fetchall())

Different Sites: [(725,)]
Count of Different Sites: []

In [ ]:
different_sites= c.execute("SELECT count( DISTINCT site_id) FROM observations;")
print("Different Sites:", different_sites.fetchall())

Different Sites: [(725,)]

In [ ]:
different_sites= c.execute("SELECT count( DISTINCT site_id) FROM observations;")
print("Different Sites:", different_sites.fetchall()[0])

Different Sites: (725,)

In [ ]:
different_sites= c.execute("SELECT count( DISTINCT site_id) FROM observations;")
print("Different Sites:", different_sites.fetchall()[0][0])

Different Sites: 725

In [ ]:
# checking the different number of sites for observations
different_sites= c.execute("SELECT count( DISTINCT site_id) FROM observations;")
print("Different Sites:", different_sites.fetchall()[0][0])

Different Sites: 725

In [ ]:
# checking the different number of sites for observations
sites_obs_range= c.execute("SELECT site_id, site_name, min(season_starting), max(season_starting), count(season_starting) FROM observations GROUP BY site_id, site_name;")
GROUP BY site_id, site_name
;")
print("Different Sites:", sites_obs_range.fetchall()[0][0])

SyntaxError: unterminated string literal (detected at line 4) (<ipython-input-16-fa585a632692>, line 4)

In [ ]:
# checking the different number of sites for observations
sites_obs_range= c.execute("SELECT site_id, site_name, min(season_starting), max(season_starting), count(season_starting) FROM observations GROUP BY site_id, site_name;")


print("Different Sites:", sites_obs_range.fetchall()[0][0])

Different Sites: ACUN

In [ ]:
# checking the different number of sites for observations
sites_obs_range= c.execute("SELECT site_id, site_name, min(season_starting), max(season_starting), count(season_starting) FROM observations GROUP BY site_id, site_name;")


print("Different Sites:", sites_obs_range.fetchall())

Different Sites: [('ACUN', 'Acuna Island', 1983, 2010, 7), ('ADAM', 'Adams Island', 2009, 2010, 2), ('ADAR', 'Cape Adare', 1982, 2018, 11), ('AILS', 'Ailsa Craig', 1983, 2019, 2), ('AITC', 'Barrientos Island (Aitcho Islands)', 1997, 2018, 27), ('AITK', 'Aitken Cove', 1983, 2018, 2), ('AKAR', 'Akarui Point', 1974, 2010, 5), ('ALAS', 'Alasheyev Bight', 2008, 2008, 1), ('ALCO', 'Alcock Island', 1989, 2020, 5), ('ALMI', 'Brown Station', 1995, 2024, 58), ('AMAN', 'Amanda Bay', 1961, 2022, 6), ('AMPH', 'Amphibolite Point', 1983, 2019, 4), ('AMUN', 'Amundsen Bay', 2009, 2009, 1), ('ANCH', 'Anchorage Island', 1976, 2016, 2), ('ANDE', 'Cape Anderson', 1983, 2018, 2), ('ANDI', 'Andresen Island Site 2', 2007, 2015, 5), ('ANDR', 'Andresen Island Site 1', 1983, 2015, 6), ('ANDS', 'Andersen Island', 2005, 2005, 1), ('ANNE', 'Cape Anne', 1986, 2018, 10), ('ANVS', 'Anvers Island South West (7 km south of Gerlache Island)', 1986, 2019, 3), ('ARDL', 'Ardley Island', 1971, 2022, 131), ('ARMS', 'Armstrong Reef', 1983, 2012, 5), ('ARTH', 'Arthurson Ridge', 2011, 2011, 1), ('ASPL', 'Aspland Island', 1976, 1976, 2), ('ASTD', 'Astrid', 2009, 2009, 1), ('ASTE', 'Astrolabe Island East', 1986, 1986, 1), ('ASTS', 'Astrolabe Island South', 1986, 1986, 1), ('ASTW', 'Astrolabe Island West', 1986, 1986, 1), ('ATKA', 'Atka', 1986, 2009, 2), ('ATRI', 'Atriceps Island', 2019, 2019, 1), ('AUST', 'Auster Islands', 1978, 2009, 4), ('AVIA', 'Avian Island', 1967, 2019, 7), ('BACH', 'Bach Quartet', 1980, 1980, 1), ('BACK', 'Backer Islands', 2010, 2010, 1), ('BAIL', 'Baily Head (Deception Island)', 1909, 2018, 12), ('BALA', 'Balaena Islands', 2011, 2011, 1), ('BARC', 'Barcroft Islands', 1982, 2012, 2), ('BARN', 'Barnard Point (Livingston Island)', 1965, 1987, 3), ('BART', 'Barton Peninsula', 1980, 2019, 67), ('BATH', 'Bath Island', 2018, 2018, 1), ('BATT', 'Cape Batterbee', 2010, 2010, 1), ('BBAY', 'Barrier Bay', 2012, 2012, 1), ('BEAG', 'Beagle Island', 2010, 2015, 2), ('BEAN', 'Beaufort Island North', 1976, 2018, 35), ('BEAR', 'Bear Peninsula', 2009, 2009, 1), ('BEAU', 'Beaufort Island', 1981, 2013, 20), ('BEAV', 'Beaver Rocks', 1986, 1986, 1), ('BECH', 'Bechervaise Island', 1990, 2001, 24), ('BELL', 'Bell Point to Kwarecki Point', 1980, 2016, 3), ('BELS', 'Cape Belsham', 1970, 2019, 4), ('BENE', 'Beneden Head', 1985, 2015, 10), ('BENN', 'Cape Bennett', 1983, 2019, 2), ('BENT', 'Benten', 1977, 2004, 17), ('BERK', 'Berkley/Cameron', 1961, 2010, 5), ('BERN', "Bernardo O'Higgins Station", 1996, 1996, 1), ('BERT', 'Berthelot Islands (excl. Green Island)', 1982, 2024, 8), ('BIEN', 'Cape Bienvenue', 1984, 2010, 3), ('BILL', 'Bills Island', 2024, 2024, 1), ('BISC', 'Biscoe Point', 1971, 2012, 33), ('BLAK', 'Blake Island', 1986, 2019, 3), ('BOLI', 'Bolingen/Lichen Island', 1981, 1981, 1), ('BONE', 'Bone Bay', 1986, 2019, 3), ('BONG', 'Bongrain Point (Pourquoi Pas Island)', 1983, 2023, 12), ('BORE', 'Boreal Point', 2015, 2015, 2), ('BOWL', 'Cape Bowles', 1976, 2010, 4), ('BOWM', 'Bowman Island', 1960, 2022, 4), ('BPTS', 'Byewater Point (south)', 1986, 2012, 2), ('BRAS', 'Brash Island', 1999, 2015, 3), ('BRAT', 'Brattstrand Bluff', 1981, 1981, 1), ('BRDM', 'Cape Bird Middle', 1983, 2021, 38), ('BRDN', 'Cape Bird North', 1982, 2021, 39), ('BRDS', 'Cape Bird South', 1983, 2021, 39), ('BREA', 'Breakwater Island', 2022, 2022, 1), ('BRIM', 'Brimstone Peak', 1980, 2019, 3), ('BRIT', "Brittannia's Figleaf", 1970, 2019, 9), ('BROW', 'Brown Bluff', 1995, 2023, 74), ('BRPW', 'Brimstone Peak (west)', 1980, 2019, 3), ('BRUC', 'Bruce Islands', 1956, 2019, 2), ('BRYA', 'Bryan Coast', 2014, 2014, 1), ('BRYE', 'Bryde Island East', 1985, 2024, 40), ('BRYS', 'Bryde Island South', 1986, 2024, 36), ('BSON', 'Brownson Islands', 2009, 2011, 2), ('BUCH', 'Buchanan Point', 1983, 1983, 1), ('BURK', 'Cape Burks', 1990, 2010, 2), ('BUSK', 'Buskin Rocks', 1971, 1971, 1), ('BYEW', 'Byewater Point', 1986, 2012, 2), ('CARL', 'Carlota Cove', 1975, 2009, 2), ('CARO', 'Caroline Bluff', 1986, 2019, 2), ('CAST', 'Castle Rock', 1986, 2012, 2), ('CASY', 'Casy Island', 1969, 1969, 1), ('CATH', 'Catharina Point', 1988, 1988, 1), ('CBAR', 'Cape Barne', 1988, 2010, 3), ('CBAY', 'Casey Bay', 2010, 2010, 1), ('CBEK', 'Cape Colbeck, Edward VII Peninsula', 2008, 2012, 6), ('CBYW', 'Casey Bay West', 2019, 2019, 1), ('CCMP', 'Chinstrap Camp', 1970, 2019, 5), ('CCOE', 'Cape Conway (east)', 1986, 2019, 4), ('CDAV', 'Cape Davis', 1984, 2005, 3), ('CECI', 'Cecilia Island', 2005, 2010, 2), ('CHAB', 'Chabrier Rock, Vaureal Peak', 1979, 2004, 4), ('CHAL', 'Cape Hallett', 1961, 2019, 30), ('CHAP', 'Chappel Island', 1979, 2010, 3), ('CHAR', 'Charcot Island', 1976, 2021, 5), ('CHAT', 'Chatos Island', 1982, 2012, 2), ('CHEA', 'Cheal Point', 1983, 1983, 1), ('CHEC', 'Crown Head (east coast)', 1983, 2019, 2), ('CHI1', 'Child Rocks Islands 1', 2005, 2005, 1), ('CHI2', 'Child Rocks Islands 2', 2005, 2005, 1), ('CHI3', 'Child Rocks Islands 3', 2005, 2005, 1), ('CHIC', 'Chick Islands', 2010, 2010, 1), ('CHII', 'Chinstrap Islet', 1972, 2013, 6), ('CHIN', 'Chinstrap Cove', 1976, 2010, 3), ('CHIS', 'Christine Island', 1971, 1986, 8), ('CHNE', 'Cape Herschel (northeast)', 1986, 1986, 1), ('CHPT', 'Charles Point', 1986, 2023, 13), ('CHRI', 'Christoffersen Island', 1983, 1983, 2), ('CHSE', 'Cape Herschel (southeast)', 1983, 2010, 3), ('CHUN', 'Cape Hunter', 1997, 2009, 2), ('CIER', 'Cierva Point', 1991, 2014, 11), ('CIPT', 'Cieslak Point', 1980, 1980, 1), ('CLAR', 'Clark Island', 2011, 2011, 1), ('CLIN', 'Cape Lindsey', 1970, 2019, 4), ('CLPT', 'Claude Point', 1984, 2013, 2), ('CMEL', 'Cape Melville', 1980, 2022, 5), ('CMID', 'Coulman Middle', 1983, 2018, 16), ('CMUR', 'Cape Murray', 1921, 2015, 2), ('CNOR', 'Coulman North', 1983, 2017, 13), ('COBA', 'Cobalescou Island', 1971, 2023, 6), ('COCK', 'Cockburn Island', 2010, 2010, 1), ('COFF', 'Coffer Island', 1983, 2019, 2), ('COLB', 'Colbeck Archipelago Unnamed 1', 2010, 2010, 1), ('CONE', 'Cone Island', 1982, 2012, 4), ('CONF', 'Confusion Island', 1978, 1978, 1), ('CONI', 'Conical Island (Aviation Islands)', 1985, 1985, 1), ('CONW', 'Cape Conway', 1986, 2019, 2), ('CORI', 'Cornwall Island', 1987, 2019, 2), ('CORM', 'Cormorant Island', 1974, 1986, 15), ('CORN', 'Cape Cornish (NE Buckle)', 1984, 2005, 3), ('COTT', 'Cape Cotter', 1981, 2018, 15), ('COUL', 'Coulman Island', 1964, 2018, 24), ('CPTW', 'Cieslak Point (west)', 1980, 2005, 2), ('CRAB', 'Crab Beach', 1970, 2019, 4), ('CRAG', 'Near Craggy Point', 1976, 2010, 2), ('CRIC', 'Cricklewood Island', 2018, 2018, 1), ('CROB', 'Cape Robertson', 1983, 2019, 2), ('CROW', 'Crown Head', 1983, 2019, 2), ('CROZ', 'Cape Crozier', 1968, 2018, 31), ('CRUZ', 'Cruzen Island', 2010, 2019, 2), ('CRWL', 'Cornwallis Island', 1976, 2019, 2), ('CRZE', 'Cape Crozier (east)', 1985, 2021, 37), ('CRZW', 'Cape Crozier (west)', 1985, 2021, 35), ('CSOU', 'Coulman South', 1983, 2018, 13), ('CURZ', 'Curzon Islands', 1997, 2010, 2), ('CUVE', 'Cuverville Island', 1971, 2024, 35), ('CVIK', 'Cape Vik', 1964, 2012, 2), ('DALR', 'Dalrymple Point', 2010, 2015, 3), ('DAMO', 'Dorian Bay/Damoy Point', 1982, 2024, 63), ('DANC', 'Danco Island', 1985, 2024, 47), ('DARB', 'Darbel Island', 1983, 2012, 3), ('DARL', 'Cape Darlington', 2019, 2019, 1), ('DARN', 'Flutter/Cape Darnley', 1961, 2022, 4), ('DARW', 'Darwin Island', 1999, 2015, 2), ('DARX', 'Darboux Island', 2012, 2012, 1), ('DAVE', 'Davey Point', 1980, 1986, 2), ('DAVI', 'Davis Island', 1960, 2010, 3), ('DAWS', 'Dawson-Lambton', 1986, 2009, 2), ('DBAY', 'Davies Bay', 2009, 2009, 1), ('DECI', 'Decimal Point', 1970, 2019, 2), ('DECS', 'Decimal Point South', 2019, 2019, 1), ('DEEI', 'Dee Island', 1965, 2010, 3), ('DELA', 'Delaite Island', 1988, 2016, 3), ('DEMA', 'Demay Point', 1977, 2015, 38), ('DENI', 'Cape Denison', 1981, 2010, 2), ('DEPT', 'Devils Point', 1965, 2019, 6), ('DESO', 'Desolation Island', 1986, 2013, 2), ('DETA', 'Detaille Island', 1957, 2024, 18), ('DEVI', 'Devil Island', 1995, 2023, 13), ('DIAZ', 'Diaz Rocks', 1986, 1986, 1), ('DIBB', 'Dibble Glacier', 2009, 2009, 1), ('DOBE', 'Dorian Beacon', 2004, 2024, 52), ('DOLL', 'Dolleman', 2009, 2009, 1), ('DOME', 'Dome Island (Aviation Islands)', 1985, 1985, 1), ('DOU1', 'Douglas Islands 1', 2005, 2005, 1), ('DOU2', 'Douglas Islands 2', 2005, 2005, 1), ('DOWN', 'Downshire Cliffs', 1982, 2013, 11), ('DREA', 'Dream Island', 1977, 2007, 9), ('DRES', 'Drescher', 1986, 2009, 2), ('DREW', 'Dream Island West (Casey Islands)', 1984, 1986, 2), ('DUKE', 'Duke of York Island', 1982, 2018, 11), ('DUND', 'Dundee Island', 1892, 2021, 2), ('DUPT', 'Duthiers Point', 1985, 2018, 10), ('DURO', 'Duroch Islands', 1965, 1990, 3), ('DURV', "d'Urville Monument", 2005, 2016, 5), ('DUTH', 'Duthoit Point', 1986, 1993, 2), ('EADI', 'Eadie Island', 1976, 2018, 2), ('EARL', 'Earle Island', 2000, 2015, 3), ('ECAP', 'East Cape', 1983, 2019, 2), ('ECKE', 'Eckener Point', 1986, 2019, 4), ('EDEN', 'Eden Rocks', 1996, 2021, 3), ('EDWA', 'Edwards Point', 1986, 2015, 2), ('EDWI', 'Edwards Islands', 2009, 2009, 1), ('EFAL', 'East side of False Bay', 1986, 1986, 1), ('EGAR', 'East 2-3 km of Cape Garry', 1986, 1986, 1), ('EIP0', 'Elephant Island (north coast point 0)', 1970, 1970, 1), ('EIP1', 'Elephant Island (north coast point 1)', 1970, 2019, 2), ('EIP2', 'Elephant Island (north coast point 2)', 1970, 2019, 3), ('EIP3', 'Elephant Island (north coast point 3)', 1970, 2019, 2), ('EIP4', 'Elephant Island (north coast point 4)', 1970, 2019, 2), ('EIP5', 'Elephant Island (north coast point 5)', 1970, 2019, 2), ('EIP6', 'Elephant Island (north coast point 6)', 2019, 2019, 1), ('ELLI', 'Ellium Island', 1983, 2019, 2), ('ELPT', 'Elephant Point', 1957, 2023, 7), ('EMEI', 'East of Meier Point', 2013, 2013, 1), ('EMER', 'Emerald Cove', 1985, 2019, 3), ('EMPE', 'Emperor Island', 1948, 2023, 28), ('ENTR', 'Entrance Point', 1909, 2024, 31), ('ENTW', 'Entrance Point West', 2018, 2018, 1), ('EPUR', 'East of Purdy Point', 2019, 2019, 1), ('ESKI', 'East of Skilling Island', 2019, 2019, 1), ('ETNA', 'Etna Island', 1960, 2015, 3), ('EVEN', 'Cape Evensen (mainland)', 1983, 2012, 4), ('EVER', 'Cape Evensen (offshore rocks)', 2012, 2012, 3), ('FARE', 'Farewell Rock', 1985, 2024, 8), ('FARI', 'False Ridge', 1976, 2010, 2), ('FBER', 'Fortenberry', 2011, 2011, 1), ('FERG', 'Ferguslie Peninsula', 1983, 2004, 2), ('FERR', 'Ferrier Peninsula', 1947, 2004, 6), ('FILD', 'Fildes Peninsula (northwest side)', 1986, 2016, 2), ('FISH', 'Fish Islands', 1983, 2024, 11), ('FITC', 'Fitchie Bay', 1983, 2004, 5), ('FIZK', 'Fizkin Island (islet northeast of Fizkin Island)', 1983, 2012, 2), ('FLIE', 'Fliess Bay', 2010, 2010, 1), ('FLOR', 'Florence Rock', 1983, 2018, 2), ('FOLD', 'Fold Island', 1977, 2022, 5), ('FORB', 'Forbes Glacier', 2008, 2010, 2), ('FORT', 'Fort Point (Greenwich Island)', 1986, 2023, 27), ('FRAE', 'Franklin Island East', 1983, 2010, 13), ('FRAM', 'Fram Islands', 1998, 2010, 2), ('FRAN', 'Franklin Island', 1964, 2012, 25), ('FRAW', 'Franklin Island West', 1981, 2010, 11), ('FRED', 'Fredriksen Island', 1983, 2019, 2), ('FRNC', 'Francais Rocks', 2015, 2015, 1), ('FRPT', 'False Round Point', 1980, 2024, 3), ('FURS', 'Fur Seal Point', 1976, 2010, 3), ('FYRC', 'Fyr Channel', 1978, 1978, 2), ('GALE', 'Galindez Island East', 1999, 2023, 10), ('GALS', 'Galindez Island South', 1999, 2012, 3), ('GAMP', 'Gam Point Area', 1980, 1980, 1), ('GARY', 'Cape Garry', 1986, 1986, 1), ('GAST', 'Gaston Islands', 1971, 2023, 14), ('GATE', 'Cape Gates', 2019, 2019, 1), ('GEDD', 'Cape Geddes', 1983, 2004, 2), ('GEOR', 'Georges Point (Ronge Island)', 1983, 2024, 63), ('GERD', 'Gerd Island', 1983, 2010, 2), ('GERL', 'Gerlache Island', 1978, 2021, 10), ('GIBA', 'Gibbon Bay', 1983, 2019, 2), ('GIBB', 'Gibbs Island', 1976, 2003, 2), ('GING', 'Ginger Island', 1948, 2023, 6), ('GLAN', 'Glandaz Point', 1982, 2019, 9), ('GNEY', 'Gibbney Island', 2010, 2010, 1), ('GOLF', 'Golfcourse Point', 1970, 2019, 2), ('GOPT', 'Gourlay Point', 1963, 2010, 24), ('GOSL', 'Gosling Islands', 1955, 1983, 4), ('GOUL', 'Gould', 2009, 2009, 1), ('GOUR', 'Gourdin Island', 1969, 2015, 7), ('GOWC', 'Gosling Islands (west coast)', 1983, 2013, 2), ('GRAP', 'Graptolite Island', 1947, 2004, 5), ('GREE', 'The Green Glen', 1970, 2019, 7), ('GREI', 'Green Island', 2012, 2023, 5), ('GREY', 'Grey Island', 1983, 2019, 2), ('GRIB', 'Georges Rib', 1970, 1970, 2), ('GRIN', 'Grinder Rock', 1985, 1985, 1), ('GUES', 'Guesalaga Island', 1985, 2024, 4), ('GULL', 'Gull Rock', 2015, 2015, 2), ('GUNN', 'Gunnerus', 1975, 2009, 3), ('HALF', 'Half Moon Island', 1986, 2024, 54), ('HALY', 'Halley', 1977, 2009, 5), ('HANE', 'Hannah Point East', 1986, 2019, 2), ('HANN', 'Hannah Point', 1958, 2019, 58), ('HANS', 'Cape Hansen, Coronation Island', 1978, 2011, 3), ('HARE', 'Harmony Point (east)', 1971, 2016, 4), ('HARM', 'Harmony Point', 1971, 2024, 10), ('HASW', 'Haswell Island', 1962, 2011, 5), ('HBAY', 'Harald Bay', 2011, 2011, 1), ('HENN', 'Hennequin Point', 1956, 1956, 1), ('HENR', 'Henry Islands', 1959, 2009, 2), ('HERO', 'Heroina Island', 1996, 2023, 9), ('HEYW', 'Heywood Island', 1965, 1965, 1), ('HINO', 'Cape Hinode', 1971, 2008, 8), ('HOLD', 'Holdfast Point (mainland and offshore rocks)', 1983, 2012, 3), ('HOLL', "Holl/O'Connor", 1961, 2010, 4), ('HOOK', 'Cape Hooker', 1986, 2019, 2), ('HOPE', 'Hope Bay', 1955, 2017, 8), ('HORS', 'Cape Hooker Rock (south)', 1986, 2019, 2), ('HOVG', 'Hovgaard Island', 2017, 2017, 1), ('HPNE', 'Hall Peninsula (northeast)', 1986, 2021, 5), ('HPSW', 'Hall Peninsula (southwest)', 1986, 2021, 8), ('HUKU', 'Hukuro Cove', 1972, 2016, 32), ('HUMB', 'Humble Island', 1955, 2011, 16), ('HUMN', 'Humphries Heights North', 2019, 2019, 1), ('HUMP', 'Humphries Heights', 1982, 2014, 8), ('HUNT', 'Hunt Island', 1986, 2019, 2), ('HURE', 'Hurd Peninsula (east)', 1987, 1987, 1), ('HURW', 'Hurd Peninsula (west)', 1987, 2010, 2), ('HUTB', 'Hut Bluff', 1970, 2019, 5), ('HYDR', 'Hydrurga Rocks', 1985, 2024, 12), ('HYDS', 'Hydrurga Rocks South', 1985, 2023, 5), ('IFOI', 'Ifo Island Area', 1998, 1998, 1), ('INAC', 'Inaccessible Island', 1986, 2019, 2), ('INEX', 'Inexpressible Island', 1963, 2019, 27), ('INTE', 'Intercurrence Island', 1985, 1985, 1), ('IOLB', 'Isles of Litwin Bay', 1980, 2005, 2), ('IVAN', 'Ivanhoff Head', 2009, 2009, 1), ('JACO', 'Jacobs Ladder', 1970, 2019, 9), ('JACP', 'Jacques Peak', 2010, 2018, 5), ('JADE', 'Jade Point', 2001, 2001, 1), ('JAME', 'Cape James', 1986, 1986, 1), ('JANE', 'Janet Rock', 2010, 2010, 1), ('JAQU', 'Jacquinot Rocks', 1990, 1990, 1), ('JASN', 'Jason Peninsula', 2012, 2012, 1), ('JESS', 'Jessie Bay', 2018, 2018, 1), ('JING', 'Jingle Island', 1983, 2012, 3), ('JOHN', "Johnson's Dock", 1987, 1987, 1), ('JONA', 'Jonassen Island', 1995, 2016, 5), ('JONE', 'Cape Jones', 1964, 2018, 13), ('JORG', 'Jorge Island', 1999, 1999, 1), ('JOUB', 'Joubin Islands', 1974, 2021, 20), ('JOUG', 'Jougla Point', 1982, 2024, 74), ('JPTI', 'Jameson Point Islands', 1986, 1986, 1), ('JPTS', 'Jameson Point (south)', 1986, 1986, 1), ('JPTV', 'Jameson Point (vicinity)', 1986, 2012, 2), ('JULE', 'Cape Jules', 1997, 2010, 2), ('KARE', 'Karelin Bay', 2019, 2019, 1), ('KATE', 'Cape Kater', 1983, 2017, 2), ('KAYR', 'Kay Rock', 1997, 2023, 4), ('KELL', 'Kellick Island', 1980, 2005, 3), ('KETL', 'Ketley Point', 1983, 2023, 4), ('KIDS', 'Kidson Island', 1988, 2010, 2), ('KILI', 'Kilifarevo Island', 2018, 2018, 1), ('KING', 'King Point', 2010, 2015, 2), ('KIRB', 'Kirby Head', 2011, 2011, 1), ('KIRT', 'Kirton/Macklin', 2006, 2006, 1), ('KITC', 'Kitchen Point', 1986, 2015, 2), ('KJEL', 'Cape Kjellman', 1986, 1986, 1), ('KLOA', 'Kloa Point', 1977, 2022, 4), ('KNOB', 'Knobble Head, Bransfield Island', 1960, 2015, 4), ('KUNO', 'Kuno Point', 2012, 2012, 1), ('KUZI', 'Kuzira Point', 1974, 2009, 6), ('LAFA', 'Lafarge Rocks', 1969, 2012, 2), ('LAGO', 'Lagotellerie Island', 1936, 2012, 8), ('LAIR', 'Lair Point', 1986, 1986, 2), ('LAJA', 'Lajarte Island', 1990, 1990, 1), ('LAKT', 'Islet next to Laktionov Island', 2012, 2012, 1), ('LARS', 'Larsen Island', 1983, 1983, 1), ('LAUF', 'Lauff Island', 1983, 2009, 2), ('LAUT', 'Lautaro Neck', 2010, 2010, 1), ('LAVO', 'Islet 1 km west of Lavosier Island', 1986, 2012, 2), ('LAZA', 'Lazarev', 2009, 2009, 1), ('LEDD', 'Ledda Bay', 2009, 2009, 1), ('LEGU', 'Cape Leguillou', 1990, 1990, 1), ('LEPP', 'Islet south of Le Petit Prince', 1980, 1980, 1), ('LEWI', 'Lewis Island', 1959, 2009, 2), ('LION', 'Lions Rump', 1957, 2023, 35), ('LITC', 'Litchfield Island', 1955, 2008, 39), ('LITW', 'Litwin Bay (southwest of Davey Point)', 1980, 2001, 2), ('LLAN', 'Llano Point', 1956, 2015, 156), ('LLOY', 'Cape Lloyd', 1976, 2010, 2), ('LOBO', 'Lobodon Island', 1985, 1985, 1), ('LOCK', 'Port Lockroy', 1996, 2022, 62), ('LOLA', 'Lola Point', 2004, 2004, 1), ('LONG', 'Long Peninsula Island', 1981, 2011, 2), ('LOOK', 'Cape Lookout', 1970, 2019, 11), ('LOUB', 'Loubat Point', 1982, 2023, 7), ('LOVI', 'Lovill Bluff', 1983, 2009, 2), ('LOWT', 'Low Tongue', 2008, 2008, 1), ('LSAY', 'Lindsay Islands', 2010, 2010, 1), ('LUIT', 'Luitpold', 2009, 2009, 1), ('MABE', 'Mabel Island', 1983, 2019, 2), ('MACK', 'MacKellar Islands', 1981, 2010, 2), ('MACO', 'Mackintosh Cove (east coast)', 1983, 1983, 1), ('MADD', 'Madder Cliff (Joinville Island)', 2004, 2024, 9), ('MADI', 'Madder Cliff Island', 2009, 2019, 5), ('MAHE', 'Maher Island', 1983, 2010, 2), ('MALL', 'Mallory Point', 2009, 2010, 2), ('MAME', 'Mame-zima', 1970, 2004, 32), ('MAND', 'Mandible Cirque', 1987, 2018, 9), ('MANS', 'Mansfield Point', 1983, 2012, 2), ('MARI', 'Mariholm', 1978, 1978, 1), ('MARR', 'Marr Bay (east coast)', 1983, 1983, 1), ('MART', 'Point Martin', 1903, 2004, 6), ('MATH', 'Matthews Island', 1970, 2019, 3), ('MAWS', 'Mawson Coast (excl. Bechervaise Island)', 2010, 2010, 1), ('MBIS', 'Mount Biscoe', 1989, 2010, 2), ('MBNE', 'Miers Bluff Cove (northeast)', 1986, 1986, 1), ('MBNW', 'Miers Bluff (northwest)', 1986, 1986, 2), ('MCDO', 'McDonald Point', 2009, 2009, 1), ('MEDL', 'Medley Rocks', 2021, 2021, 2), ('MEGA', 'Megaptera Island', 1986, 1986, 1), ('MEHO', 'Meholmen Island', 1984, 1984, 2), ('MEIE', 'Meier Point', 2012, 2012, 1), ('MERR', 'Merritt Island', 2007, 2009, 2), ('MERT', 'Mertz Glacier', 2009, 2009, 1), ('METC', 'Metchnikoff Point', 1983, 2023, 2), ('METH', 'Methuen Cove', 1983, 2018, 2), ('MGLE', 'Mount Gleadell', 2009, 2009, 1), ('MICH', 'Michelsen Island', 1957, 1983, 4), ('MIDA', 'Midas Island', 1971, 2015, 5), ('MIDD', 'Middle Island', 2022, 2022, 1), ('MIDG', 'Hollin/Midgley', 1961, 2010, 5), ('MIER', 'Miers Bluff', 1986, 2010, 3), ('MIKK', 'Mikkelsen Harbor (Trinity Island)', 1983, 2024, 37), ('MILL', 'Mill Cove', 2004, 2004, 1), ('MIZU', 'Mizukuguri Cove', 1975, 2004, 23), ('MLGE', 'McLeod Glacier (east)', 1978, 1978, 1), ('MLGW', 'McLeod Glacier (west)', 1978, 1978, 1), ('MOEI', 'Moe Island', 1978, 1978, 1), ('MONA', 'Cape Monaco', 1978, 1978, 1), ('MONR', 'Monroe Island', 1983, 1983, 1), ('MONU', 'Monument Rocks', 1983, 2019, 2), ('MOOT', 'Moot Point', 2005, 2022, 20), ('MOPT', 'Monroe Point', 1986, 2012, 2), ('MORE', 'Moreton Point', 1983, 1983, 1), ('MORR', 'Morris Rocks', 1988, 1988, 1), ('MOSS', 'West coast of Mossman Peninsula', 1983, 2018, 2), ('MOYE', 'Moyes', 1978, 1978, 2), ('MPNC', 'Moreton Point North Coast', 1983, 1983, 1), ('MPTE', 'Macaroni Point (east)', 1953, 2011, 4), ('MPTW', 'Macaroni Point (west)', 1986, 2011, 2), ('MRII', 'Mount Riiser-Larsen', 1996, 2009, 2), ('MUCK', 'Muckle Bluff', 1970, 2019, 5), ('MURR', 'Murray Islands', 1983, 2018, 2), ('MYAL', 'Myall/McMahon', 2010, 2010, 1), ('NANC', 'Nancy Rock', 1979, 2016, 4), ('NCAP', "North Cape (d'Urville Island)", 1960, 1960, 1), ('NCOI', 'North of Cornwall Island', 1987, 1987, 1), ('NDUT', 'North of Duthoit Point', 1986, 1986, 1), ('NEBL', 'Nebles Point', 1986, 1986, 1), ('NEDU', "Northeast D'Urville Island", 2021, 2021, 2), ('NEIS', 'Nelly Island', 1961, 2010, 6), ('NEKO', 'Neko Harbor (Andvord Bay)', 1986, 2024, 83), ('NELL', 'Nella/Thalla Islands', 1985, 2010, 2), ('NEPT', 'Nelly Point', 1970, 2015, 3), ('NESM', 'Northeast of Smigg

In [ ]:
q_sites_obs_range= """
SELECT site_id
      ,site_name
      ,min(season_starting)
      ,max(season_starting)
      ,count(season_starting) 
      FROM observations 
      GROUP BY 
      site_id
      ,site_name;
""""

# checking the different number of sites for observations
df_sites_obs_range= pd.read_sql(q_sites_obs_range, conn)

df_sites_obs_range

SyntaxError: unterminated string literal (detected at line 11) (<ipython-input-19-6c2cdce3aef3>, line 11)

In [ ]:
q_sites_obs_range = """SELECT site_id
      ,site_name
      ,min(season_starting)
      ,max(season_starting)
      ,count(season_starting) 
      FROM observations 
      GROUP BY 
      site_id
      ,site_name;"""
      
df_sites_obs_range= pd.read_sql(q_sites_obs_range, conn)

df_sites_obs_range

,site_id,site_name,min(season_starting),max(season_starting),count(season_starting)
0,ACUN,Acuna Island,1983,2010,7
1,ADAM,Adams Island,2009,2010,2
2,ADAR,Cape Adare,1982,2018,11
3,AILS,Ailsa Craig,1983,2019,2
4,AITC,Barrientos Island (Aitcho Islands),1997,2018,27
...,...,...,...,...,...
720,YTRE,Ytrehovdeholmen,1975,2004,18
721,YULE,Yule Bay,2019,2019,1
722,ZAWA,Zawadski Stacks,1980,2016,2
723,ZEDI,Zed Island,1986,2013,2
724,ZIGZ,Zig Zag Island,1986,1986,1

In [ ]:
q_sites_obs_range = """SELECT site_id
      ,site_name
      ,min(season_starting) AS "First observation year"
      ,max(season_starting) AS "Last observation year"
      ,count(season_starting) AS "Number of observations"
      FROM observations 
      GROUP BY 
      site_id
      ,site_name;"""
      
df_sites_obs_range= pd.read_sql(q_sites_obs_range, conn)

df_sites_obs_range

,site_id,site_name,First observation year,Last observation year,Number of observations
0,ACUN,Acuna Island,1983,2010,7
1,ADAM,Adams Island,2009,2010,2
2,ADAR,Cape Adare,1982,2018,11
3,AILS,Ailsa Craig,1983,2019,2
4,AITC,Barrientos Island (Aitcho Islands),1997,2018,27
...,...,...,...,...,...
720,YTRE,Ytrehovdeholmen,1975,2004,18
721,YULE,Yule Bay,2019,2019,1
722,ZAWA,Zawadski Stacks,1980,2016,2
723,ZEDI,Zed Island,1986,2013,2
724,ZIGZ,Zig Zag Island,1986,1986,1

In [ ]:
q_sites_obs_range = """SELECT site_id
      ,site_name
      ,min(season_starting) AS "First observation year"
      ,max(season_starting) AS "Last observation year"
      ,max(season_starting) - min(season_starting) AS "Observation range in years"
      ,count(season_starting) AS "Number of observations"
      FROM observations 
      GROUP BY 
      site_id
      ,site_name;"""
      
df_sites_obs_range= pd.read_sql(q_sites_obs_range, conn)

df_sites_obs_range

,site_id,site_name,First observation year,Last observation year,Observation range in years,Number of observations
0,ACUN,Acuna Island,1983,2010,27,7
1,ADAM,Adams Island,2009,2010,1,2
2,ADAR,Cape Adare,1982,2018,36,11
3,AILS,Ailsa Craig,1983,2019,36,2
4,AITC,Barrientos Island (Aitcho Islands),1997,2018,21,27
...,...,...,...,...,...,...
720,YTRE,Ytrehovdeholmen,1975,2004,29,18
721,YULE,Yule Bay,2019,2019,0,1
722,ZAWA,Zawadski Stacks,1980,2016,36,2
723,ZEDI,Zed Island,1986,2013,27,2
724,ZIGZ,Zig Zag Island,1986,1986,0,1

In [ ]:
q_sites_obs_range = """SELECT site_id
      ,site_name
      ,min(season_starting) AS "First observation year"
      ,max(season_starting) AS "Last observation year"
      ,max(season_starting) - min(season_starting)+1 AS "Observation range in years"
      ,count(season_starting) AS "Number of observations"
      FROM observations 
      GROUP BY 
      site_id
      ,site_name;"""
      
df_sites_obs_range= pd.read_sql(q_sites_obs_range, conn)

df_sites_obs_range

,site_id,site_name,First observation year,Last observation year,Observation range in years,Number of observations
0,ACUN,Acuna Island,1983,2010,28,7
1,ADAM,Adams Island,2009,2010,2,2
2,ADAR,Cape Adare,1982,2018,37,11
3,AILS,Ailsa Craig,1983,2019,37,2
4,AITC,Barrientos Island (Aitcho Islands),1997,2018,22,27
...,...,...,...,...,...,...
720,YTRE,Ytrehovdeholmen,1975,2004,30,18
721,YULE,Yule Bay,2019,2019,1,1
722,ZAWA,Zawadski Stacks,1980,2016,37,2
723,ZEDI,Zed Island,1986,2013,28,2
724,ZIGZ,Zig Zag Island,1986,1986,1,1

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites'
        )

fig.show()

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={
                "site_name": "Site Name"
        }
        )

fig.show()

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={
                "site_name": "Site Name"
        }
        )
fig.update_layout(
        height=600
)


fig.show()

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={
                "site_name": "Site Name"
        }
        )
fig.update_layout(
        height=800,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15
        )
)


fig.show()

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={
                "site_name": "Site Name"
        }
        )
fig.update_layout(
        height=800,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15,
                orientation="h",
        )
)


fig.show()

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={
                "site_name": "Site Name"
        }
        )
fig.update_layout(
        height=800,
        width=1600,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15,
                orientation="h",
        )
)


fig.show()

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={
                "site_name": "Site Name"
        }
        )
fig.update_layout(
        height=800,
        width=1200,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15,
                orientation="h",
        )
)


fig.show()

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={
                "site_name": "Site Name"
        }
        )
fig.update_layout(
        height=800,
        width=1200,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15,
                orientation="h",
        )
)


fig.show()

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='<b>Observation range in years</b>',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={
                "site_name": "<b>Site Name</b>"
        }
        )
fig.update_layout(
        height=800,
        width=1200,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15,
                orientation="h",
        )
)


fig.show()

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['site_id', 'site_name', 'First observation year', 'Last observation year', 'Observation range in years', 'Number of observations'] but received: <b>Observation range in years</b>

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='<b>Observation range in years</b>',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={
                "site_name": "Site Name"
        }
        )
fig.update_layout(
        height=800,
        width=1200,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15,
                orientation="h",
        )
)


fig.show()

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['site_id', 'site_name', 'First observation year', 'Last observation year', 'Observation range in years', 'Number of observations'] but received: <b>Observation range in years</b>

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='<b>Observation range in years</b>',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={"site_name": "Site Name"}
        )
fig.update_layout(
        height=800,
        width=1200,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15,
                orientation="h",
        )
)


fig.show()

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['site_id', 'site_name', 'First observation year', 'Last observation year', 'Observation range in years', 'Number of observations'] but received: <b>Observation range in years</b>

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={"site_name": "Site Name"}
        )
fig.update_layout(
        height=800,
        width=1200,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15,
                orientation="h",
        )
)


fig.show()

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={"site_name": "Site Name"}
        )
fig.update_layout(
        height=800,
        width=1200,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15,
                orientation="h",
        )
        xaxis_title='Observation range years',
        yaxis_title='<b>Site name</b>'
)


fig.show()

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-36-5dbaa2b74d05>, line 16)

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={"site_name": "Site Name"}
        )
fig.update_layout(
        height=800,
        width=1200,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15,
                orientation="h",
        ),
        xaxis_title='Observation range years',
        yaxis_title='<b>Site name</b>'
)


fig.show()

In [ ]:
import plotly.express as px

fig = px.bar(
        df_sites_obs_range,
        x='Observation range in years',
        y='site_name',
        base='First observation year',
        orientation='h',
        color='Number of observations',
        title='Observation Ranges by Sites',
        labels={"site_name": "Site Name"}
        )
fig.update_layout(
        height=800,
        width=1200,
        coloraxis_colorbar=dict(
                title="Number of Observations",
                thicknessmode="pixels",
                thickness=15,
                orientation="h",
        ),
        xaxis_title='<b>Observation range years</b>',
        yaxis_title='<b>Site name</b>'
)


fig.show()

In [ ]:
# boxplot

fig_boxplot = px.box(
        df_sites_obs_range['Number of observations'],
        x='Number of observation variance',
        title='Varying number of observations for the sites'
        )

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['Number of observations'] but received: Number of observation variance

In [ ]:
# boxplot

fig_boxplot = px.box(
        df_sites_obs_range['Number of observations'],
        x='Number of observation variance',
        title='Varying number of observations for the sites'
        )

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['Number of observations'] but received: Number of observation variance

In [ ]:
# boxplot

fig_boxplot = px.box(
        df_sites_obs_range[['Number of observations']],
        x='Number of observation variance',
        title='Varying number of observations for the sites'
        )

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['Number of observations'] but received: Number of observation variance

In [ ]:
# boxplot

fig_boxplot = px.box(
        df_sites_obs_range[['Number of observations']],
        x='Number of observations',
        title='Varying number of observations for the sites'
        )

In [ ]:
# boxplot

fig_boxplot = px.box(
        df_sites_obs_range[['Number of observations']],
        x='Number of observations',
        title='Varying number of observations for the sites'
        )

fig_boxplot.show()

In [ ]:
# boxplot

fig_boxplot = px.box(
        df_sites_obs_range[['Number of observations']],
        points="all",
        y='Number of observations',
        title='Varying number of observations for the sites'
        )

fig_boxplot.update_layout(
        yaxis=dict(
                showgrid=True,
                gridcolor='rgb(200, 200, 200)',
                gridwidth=1,
        ),
        paper_bgcolor='rgb(243, 243, 243)',
    plot_bgcolor='rgb(243, 243, 243)',
        width=800,
)


fig_boxplot.show()